version: '2'

services: 
    deno-beers: 
        container_name: deno-beers
        build: 
            context: .
            dockerfile: dockerfile
        ports: 
            - "8080:8080"
        networks: 
            - deno-network
    mongodb:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"
        networks: 
            - deno-network

networks: 
    deno-network:
        driver: bridge
